//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-646 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.14 at 02:38:02 PM BRT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.ntkvaccine.com.br/aplicativo", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package br.com.service.retorno;
